# Commands to start on workspace startup
tasks:
  - name: hardhat repo
    init: npm install
    command: npx hardhat node --watch
  - name: frontend repo
    init: cd frontend && npm install
    command: npm start

ports:
  - port: 8545
    onOpen: notify
    visibility: public
  - port: 3000
    onOpen: notify
    visibility: public